spring:
  application:
    name: FoodGram
  main:
    allow-bean-definition-overriding: true
  data:
    mongodb:
      uri: mongodb+srv://it22143204:ZfTg6QRxfTY1Fgam@cluster0.any78ur.mongodb.net/FoodGram?retryWrites=true&w=majority&appName=Cluster0
server:
  port: 8080
  error:
    include-exception: true
    include-message: always
imagekit:
  private-key: private_kTbgSn90Tcs/CikohjpO3uqxxIM=
